### ISSUE TITLE
Error when a command prefix contains quotes "

### ISSUE THREAD

**Issue by Blueyescat** [iBlitzkriegi/Vixio#132]
**Describe the bug**
Throws NPE when a prefix contains quotes but not starts and ends with quotes, i found it when i made this mistake: `"!prefix ", !"prefix "`

**To Reproduce**
```vb
prefixes: !"xy "
prefixes: "
prefixes: !"
prefixes: x""
prefixes: "x
```
`prefixes: ""` won't give error

**Errors**
```md
#!#! java.lang.NullPointerException
#!#! at me.iblitzkriegi.vixio.commands.DiscordCommandFactory.add(DiscordCommandFactory.java:238)
#!#! at me.iblitzkriegi.vixio.commands.DiscordCommandRegistry.init(DiscordCommandRegistry.java:130)
```

**Expected behavior**
It should take the first prefix as **`!"xy "`**

**Comment by TobyMinceraft** [comment]
That would be caused by Skript itself, not Vixio.
The way Skript treats quotes is directly, not as text. To make Skript treat quotes as text, you'll need to double them.

Your example: `!"x "`
What is should be: `!""x ""`

**Comment by Blueyescat** [comment]
not related :P
