### ISSUE TITLE
reset reactions of message

### ISSUE THREAD

**Issue by Jyoooo** [iBlitzkriegi/Vixio#156]
**Describe the bug**
End of error.

**To Reproduce**
```vb
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! [Skript] Severe Error:
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Something went horribly wrong with Skript.
[21:35:44 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[21:35:44 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[21:35:44 ERROR]: #!#! Following plugins are probably related to this error in some way:
[21:35:44 ERROR]: #!#! Vixio (http://vixio.space)
[21:35:44 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[21:35:44 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[21:35:44 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[21:35:44 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[21:35:44 ERROR]: #!#! Only if the author tells you to do so, report it as Skript issue (url below)
[21:35:44 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Stack trace:
[21:35:44 ERROR]: #!#! java.lang.UnsupportedOperationException: This expression can only be changed using Vixio's changer effects. Please report how you got this error to show at https://github.com/iBlitzkriegi/Vixio/issues
[21:35:44 ERROR]: #!#!     at me.iblitzkriegi.vixio.changers.ChangeableSimpleExpression.change(ChangeableSimpleExpression.java:13)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:278)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.function.ScriptFunction.execute(ScriptFunction.java:93)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.function.Function.execute(Function.java:119)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:204)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[21:35:44 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[21:35:44 ERROR]: #!#!     at me.iblitzkriegi.vixio.events.base.BaseEvent.lambda$null$1(BaseEvent.java:139)
[21:35:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[21:35:44 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
[21:35:44 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[21:35:44 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[21:35:44 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[21:35:44 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[21:35:44 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Version Information:
[21:35:44 ERROR]: #!#!   Skript: 2.2-dev37c
[21:35:44 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[21:35:44 ERROR]: #!#!   Minecraft: 1.12.2
[21:35:44 ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[21:35:44 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Server platform: Spigot
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Current node: null
[21:35:44 ERROR]: #!#! Current item: null
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Thread: Server thread
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! Language: english
[21:35:44 ERROR]: #!#! Link parse mode: STRICT
[21:35:44 ERROR]: #!#!
[21:35:44 ERROR]: #!#! End of Error.
[21:35:44 ERROR]: #!#!
```
**Expected behavior**
Reset react

and my code

```vb
function noPurchased(m: user, e: channel):
    set {_idm2} to id of {_m}
    reset reactions of {shopem.%{_idm2}%}

**Comment by Jyoooo** [comment]
i solved
i didn't write with "bot" lol
