### ISSUE TITLE
Link command doesn't work

### ISSUE THREAD

**Issue by AlienKoad** [iBlitzkriegi/Vixio#158]
**Describe the bug**
link command doesn't work when i type link in discord

**To Reproduce**
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! [Skript] Severe Error:
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
[20:39:29 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
[20:39:29 ERROR]: #!#! and check whether this error has already been reported.
[20:39:29 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
[20:39:29 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
[20:39:29 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
[20:39:29 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! Stack trace:
[20:39:29 ERROR]: #!#! java.lang.IllegalStateException: The Requester has been shutdown! No new requests can be requested!
[20:39:29 ERROR]: #!#!     at net.dv8tion.jda.core.requests.Requester.request(Requester.java:85)
[20:39:29 ERROR]: #!#!     at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:338)
[20:39:29 ERROR]: #!#!     at net.dv8tion.jda.core.requests.RestAction.queue(RestAction.java:296)
[20:39:29 ERROR]: #!#!     at me.iblitzkriegi.vixio.effects.message.EffReplyWith.execute(EffReplyWith.java:58)
[20:39:29 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
[20:39:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[20:39:29 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[20:39:29 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
[20:39:29 ERROR]: #!#!     at me.iblitzkriegi.vixio.commands.DiscordCommand.lambda$execute$2(DiscordCommand.java:77)
[20:39:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[20:39:29 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[20:39:29 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:722)
[20:39:29 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[20:39:29 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
[20:39:29 ERROR]: #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
[20:39:29 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! Version Information:
[20:39:29 ERROR]: #!#!   Skript: 2.2-dev27
[20:39:29 ERROR]: #!#!   Bukkit: 1.8.7-R0.1-SNAPSHOT
[20:39:29 ERROR]: #!#!   Minecraft: 1.8.7
[20:39:29 ERROR]: #!#!   Java: 1.8.0_201 (Java HotSpot(TM) 64-Bit Server VM 25.201-b09)
[20:39:29 ERROR]: #!#!   OS: Windows 10 amd64 10.0
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! Running CraftBukkit: false
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! Current node: null
[20:39:29 ERROR]: #!#! Current item: reply with "Please type /link ingame to get your verification code"
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! Thread: Server thread
[20:39:29 ERROR]: #!#!
[20:39:29 ERROR]: #!#! End of Error.
[20:39:29 ERROR]: #!#!

**Comment by iBlitzkriegi** [comment]
This is because you've logged out and logged back in of your bot without restarting the server. JDA and Discord don't like this. Restart your server and it'll be fine.
