### ISSUE TITLE
Errors on server restart

### ISSUE THREAD

**Issue by JeepSmash** [iBlitzkriegi/Vixio#19]
```
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! End of Error.
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! Link parse mode: DISABLED
19.12 23:39:18 [Server] ERROR #!#! Language: english
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! Thread: Server thread
19.12 23:39:18 [Server] ERROR #!#! Current item: me.iblitzkriegi.vixio.effects.EffSendUserMessage
19.12 23:39:18 [Server] ERROR #!#! Current node: null
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! Running Paper (or compatible): false
19.12 23:39:18 [Server] ERROR #!#! Running Spigot (or compatible): true
19.12 23:39:18 [Server] ERROR #!#! Running CraftBukkit: false
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.6.2.el6.x86_64
19.12 23:39:18 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
19.12 23:39:18 [Server] ERROR #!#!   Minecraft: 1.12.2
19.12 23:39:18 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
19.12 23:39:18 [Server] ERROR #!#!   Skript: 2.2-dev32
19.12 23:39:18 [Server] ERROR #!#! Version Information:
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source)
19.12 23:39:18 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
19.12 23:39:18 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
19.12 23:39:18 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
19.12 23:39:18 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
19.12 23:39:18 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
19.12 23:39:18 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.12 23:39:18 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
19.12 23:39:18 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
19.12 23:39:18 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
19.12 23:39:18 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
19.12 23:39:18 [Server] ERROR #!#!     at me.iblitzkriegi.vixio.effects.EffSendUserMessage.execute(EffSendUserMessage.java:30)
19.12 23:39:18 [Server] ERROR #!#! java.lang.NullPointerException
19.12 23:39:18 [Server] ERROR #!#! Stack trace:
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
19.12 23:39:18 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
19.12 23:39:18 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
19.12 23:39:18 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
19.12 23:39:18 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
19.12 23:39:18 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
19.12 23:39:18 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
19.12 23:39:18 [Server] ERROR #!#! skRayFall (http://sk.rayfall.net/) skDragon skUtilities (https://tim740.github.io/) ExtrasSK SkQuery skript-votifier-hook 
19.12 23:39:18 [Server] ERROR #!#! Here is full list of them:
19.12 23:39:18 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
19.12 23:39:18 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
19.12 23:39:18 [Server] ERROR #!#! Something went horribly wrong with Skript.
19.12 23:39:18 [Server] ERROR #!#! 
19.12 23:39:18 [Server] ERROR #!#! [Skript] Severe Error:
19.12 23:39:18 [Server] ERROR #!#! 
```

I had no problems with errors prior to adding latest version of vixio.  Errors started after second server restart after install.  Sometimes it will crash upon restart sometimes it will continue to work normal after the errors.

**Comment by iBlitzkriegi** [comment]
This is very weird, i need more information to solve. Could you give me the code that causes it and surrounding code?
