### ISSUE TITLE
[FIX] - LavaPlayer Bug

### ISSUE THREAD

**Issue by NouzMC** [iBlitzkriegi/Vixio#194]
ERROR:

`[01:50:04 ERROR]: [com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of oWYp1xRPH5g
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[?:?]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[?:?]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.RuntimeException: Not success status code: 403`

CODE:

`discord command test [<text>]:
    prefixes: {@prefixes}
    bots: {@botName}
    trigger:    
        search youtube for arg-1 and store the results in {_results::*}
        play {_results::1}`

**Comment by ilsubyeega** [comment]
by the way, are you using vixio 2.0.1 (released on #general)

**Comment by wohahobg** [comment]
> by the way, are you using vixio 2.0.1 (released on #general)

I have using the general one from Discord but again has same problem.
