### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by AdxmGG** [iBlitzkriegi/Vixio#197]
I'm getting this bug in my console on load. Anything i'm doing wrong?
```
[20:39:35] [JDA RateLimit-Queue Pool - Thread 1/ERROR]: Requester system encountered an internal error
java.lang.NoSuchMethodError: okhttp3.Response.close()
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:251) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344) [Vixio.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[20:39:35] [Craft Scheduler Thread - 7/INFO]: Login Successful!
[20:39:35] [JDA RateLimit-Queue Pool - Thread 2/ERROR]: Requester system encountered an internal error
java.lang.NoSuchMethodError: okhttp3.Response.close()V
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:251) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344) [Vixio.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[20:39:35] [Server thread/INFO]: com.mojang.authlib.GameProfile@15f26d2e[id=6390d2d0-c1ea-4f39-9ce4-8875fd5e7237,name=Minehut,properties={textures=[com.mojang.authlib.properties.Property@3bd444c4]},legacy=false] (/10.30.3.180:49109) lost connection: Disconnected
[20:39:35] [Server thread/INFO]: com.mojang.authlib.GameProfile@71d2c071[id=0ca56b63-b5b3-449e-9a55-514ff4bbd949,name=StR1NgZz,properties={textures=[com.mojang.authlib.properties.Property@4527946b]},legacy=false] (/10.30.2.7:44793) lost connection: Disconnected```

**Comment by AdxmGG** [comment]
More errors, spamming my console.
```[22:34:34] [JDA RateLimit-Queue Pool - Thread 4/ERROR]: Requester system encountered an internal error
java.lang.NoSuchMethodError: okhttp3.Response.close()V
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:251) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344) [Vixio.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[22:34:34] [ForkJoinPool.commonPool-worker-0/ERROR]: RestAction queue returned failure: [NoSuchMethodError] okhttp3.Response.close()V
[22:34:34] [Server thread/INFO]: [444] [EPIC] J1Slxx [PVP]: noo
[22:34:35] [JDA RateLimit-Queue Pool - Thread 1/ERROR]: Requester system encountered an internal error
java.lang.NoSuchMethodError: okhttp3.Response.close()V
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:251) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:133) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:116) ~[Vixio.jar:?]
	at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:344) [Vixio.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[22:34:35] [ForkJoinPool.commonPool-worker-0/ERROR]: RestAction queue returned failure: ```
