### ISSUE TITLE
Bug On Chat

### ISSUE THREAD

**Issue by monkey00000** [iBlitzkriegi/Vixio#236]
Code:

On chat:
    send "<%event-player%> %message%" to channel with id "{@chat}" with "ChatBot"
Crash when I'm chat:
[22:34:20] [Async Chat Thread - #10/INFO]: <monkey00000> OuO
[22:34:20] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> OuO","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663389833414180876","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:34:21.473000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:34:20] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> OuO","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663389833414180876","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:34:21.473000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:34:20] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> OuO","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663389833414180876","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:34:21.473000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:36:18] [Async Chat Thread - #11/INFO]: <monkey00000> w
[22:36:18] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> w","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663390329961185301","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:36:19.859000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:36:18] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> w","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663390329961185301","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:36:19.859000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:36:18] [JDA MainWS-ReadThread/ERROR]: [net.dv8tion.jda.internal.requests.WebSocketClient] Got an unexpected error. Please redirect following message to the devs:
	MESSAGE_CREATE -> {"mention_everyone":false,"pinned":false,"attachments":[],"author":{"bot":true,"id":"631514016291881003","avatar":null,"username":"MagicWar-ChatBot","discriminator":"8322"},"flags":0,"type":0,"mention_roles":[],"nonce":null,"edited_timestamp":null,"content":"<monkey00000> w","tts":false,"mentions":[],"member":{"premium_since":null,"nick":null,"joined_at":"2020-01-05T10:50:07.725749+00:00","roles":["663333404258861066","656815182185627650"],"hoisted_role":"656815182185627650","deaf":false,"mute":false},"guild_id":"656814795936366611","id":"663390329961185301","embeds":[],"channel_id":"663328337401348097","timestamp":"2020-01-05T14:36:19.859000+00:00"}
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_221]
	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_221]
	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_221]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.13.2.jar:git-Paper-645]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-645]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:873) ~[?:?]
	at net.dv8tion.jda.internal.entities.EntityBuilder.createMessage(EntityBuilder.java:855) ~[?:?]
	at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:59) ~[?:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:37) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:838) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:737) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:716) ~[?:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:876) ~[?:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:270) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:990) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:749) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[?:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[?:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]
[22:36:24] [Server thread/INFO]: Stopping the server
[22:36:24] [Server thread/INFO]: Stopping server
[22:36:24] [Server thread/INFO]: [MythicSkriptAddon] Disabling MythicSkriptAddon v0.97a-SNAPSHOT
[22:36:24] [Server thread/INFO]: mmSkriptAddon disabled!
[22:36:24] [Server thread/INFO]: [SharpSK] Disabling SharpSK v1.6.3
[22:36:24] [Server thread/INFO]: [SharpSK] Successfully disabled.
[22:36:24] [Server thread/INFO]: [MythicMobs] Disabling MythicMobs v4.7.0-SNAPSHOT
[22:36:24] [Server thread/INFO]: [MythicMobs] Disabling Mythic Mobs...[0m
[22:36:24] [Server thread/INFO]: [MythicMobs] All active settings have been saved.[0m
[22:36:24] [Server thread/INFO]: [MythicMobs] v4.7.0-SNAPSHOT has been Disabled![0m
[22:36:24] [Server thread/INFO]: [Vixio] Disabling Vixio v2.0.3
[22:36:24] [Server thread/INFO]: [HolographicExtension] Disabling HolographicExtension v1.10.8
[22:36:24] [Server thread/INFO]: [HolographicExtension] Disabling HolographicExtension v1.10.8
[22:36:24] [Server thread/INFO]: [Skellett] Disabling Skellett v1.9.8
[22:36:24] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.0;02b731f
[22:36:24] [Server thread/INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[22:36:24] [Server thread/INFO]: [Ersatz] Disabling Ersatz v1.0
[22:36:24] [Server thread/INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.0
[22:36:24] [Server thread/INFO]: [SkQuery] Disabling SkQuery v4.1.1
[22:36:24] [Server thread/INFO]: [skUtilities] Disabling skUtilities v0.9.2
[22:36:24] [Server thread/INFO]: [skDragon] Disabling skDragon v0.15
[22:36:24] [Server thread/INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.4
[22:36:24] [Server thread/INFO]: [Skript] Disabling Skript v2.4.1
[22:36:24] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.1.0-beta-1;7039dc8
[22:36:24] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[22:36:24] [Server thread/INFO]: [Citizens] Disabling Citizens v2.0.26-SNAPSHOT (build 1793)
[22:36:24] [Server thread/INFO]: Saving players
[22:36:24] [Server thread/INFO]: monkey00000 lost connection: Server closed
[22:36:24] [Server thread/INFO]: monkey00000 left the game
[22:36:24] [Server thread/INFO]: Saving worlds
[22:36:24] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[22:36:24] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
[22:36:24] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[22:36:24] [JDA Shutdown Hook/WARN]: Exception in thread "JDA Shutdown Hook" java.lang.IllegalStateException: zip file closed
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.zip.ZipFile.ensureOpen(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.zip.ZipFile.getEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.jar.JarFile.getEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.jar.JarFile.getJarEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.closeAudioConnections(JDAImpl.java:657)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:631)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.shutdown(JDAImpl.java:623)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.lang.Thread.run(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: Exception in thread "JDA Shutdown Hook" java.lang.IllegalStateException: zip file closed
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.zip.ZipFile.ensureOpen(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.zip.ZipFile.getEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.jar.JarFile.getEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.util.jar.JarFile.getJarEntry(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.closeAudioConnections(JDAImpl.java:657)
[22:36:24] [JDA Shutdown Hook/WARN]: 	at net.dv8tion.jda.internal.JDAImpl.shutdownInternals(JDAImpl.java:631)

**Comment by ilsubyeega** [comment]
Can you check with latest vixio version?

**Comment by XxRogerxX-SPMC** [comment]
Change `%event-player%` only with `%player%`
