### ISSUE TITLE
fail bot can't came online i spigot 1.15.2 and skript version 2.4.1

### ISSUE THREAD

**Issue by phiko-misc** [iBlitzkriegi/Vixio#244]
I see error about Vixio if i restart my server

I will like if your fix the probling so i can make discord robot in spigot 1.15.2 and skript version 2.4.1
 my error code is: 

```
13.03 12:55:58 [Server] Server thread/WARN [Skript] Task #12 for Skript v2.4.1 generated an exception
13.03 12:55:58 [Server] INFO java.lang.IncompatibleClassChangeError: Found interface ch.njol.skript.util.Color, but class was expected
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.registration.TypeConverters.lambda$register$0(TypeConverters.java:27) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.registrations.Classes.parse(Classes.java:462) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:95) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:84) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.UnparsedLiteral.getConvertedExpression(UnparsedLiteral.java:1) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.effects.EffChange.init(EffChange.java:215) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.Statement.parse(Statement.java:59) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1006) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.util.scope.EffectSection$1.<init>(EffectSection.java:134) ~[?:?]
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.util.scope.EffectSection.loadSection(EffectSection.java:134) ~[?:?]
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.scopes.ScopeMakeEmbed.init(ScopeMakeEmbed.java:125) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:252) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.Condition.parse(Condition.java:81) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1086) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.TriggerSection.<init>(TriggerSection.java:54) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.Conditional.<init>(Conditional.java:44) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1093) ~[?:?]
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.commands.DiscordCommandFactory.add(DiscordCommandFactory.java:263) ~[?:?]
13.03 12:55:58 [Server] INFO at me.iblitzkriegi.vixio.commands.DiscordCommandRegistry.init(DiscordCommandRegistry.java:130) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1264) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.lang.SkriptParser.parseEvent(SkriptParser.java:1235) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:684) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:409) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:428) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.lambda$0(ScriptLoader.java:347) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:380) ~[?:?]
13.03 12:55:58 [Server] INFO at ch.njol.skript.Skript$2.run(Skript.java:534) ~[?:?]
13.03 12:55:58 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-800b93f-29737cc]
13.03 12:55:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**Comment by HardstylesDev** [comment]
Code? I've had the same error when I updated to newer Skript versions.

**Comment by Pirat0303** [comment]
> Code? I've had the same error when I updated to newer Skript versions.

okay so you say i need do downgrade my skript version for the Vixio work

**Comment by HardstylesDev** [comment]
no i'm saying your code seems to have some sort of error in it which is why i'm asking for your code...

**Comment by Pirat0303** [comment]
ohh okay my code is 
```
options:
	botname: CubeAwesome_rank
	Token: no seen
	prefixe: !
	#Discord ranks - bruges til at linke folks kontorer#
	staff: "Staff"
	mod: "Mod"
	hjælper: "Hjælper"
	role2: "donater2"
	role1: "donater1"
	role3: "donater3"

	kategori: Donater-rum #bruges så folk der har rank selv kan leve en discord channel
	kategori1: support ticked #bruges så folk der har brug for hjælp kan lave et suprt sagr
	channelid: 645636511194415141 #bestemmer hvilken channel folk skal skrive i for at lave en support sag
	delay: 60 #bestemmer sekunder hvor lag tid der skal gå før botten sletter sin besked i !support commanden
	delay1: 5 #bestemmer sekunder hvor lag tid der skal gå før botten sletter sin besked i !link commanden
	admins: "indsæt admins rolle kode her" #Du finder den inde på  discord i server indstillinger. Du skal bruge dette her til at bestme hvem der kan clear en chat

on skript load:
	login to "{@Token}" with the name "{@botname}"
	mark "{@botname}" as playing "!hjælp for kommandor"

discord command make <text>:
	bots: {@botname}
	prefixes: {@prefixe}
	trigger:
		if arg-1 is set:
			if event-member has role named {@role1}, {@role2}, {@role3} or {@staff}:
				create voice channel:
					set the name of the channel to arg-1
					set the parent of the channel to category named "{@kategori}"
					allow event-member permissions (manage channel, voice connect, voice mute others and voice deaf others) in event-channel
					create the channel in event-guild

discord command support-slut:
	bots: {@botname}
	prefixes: {@prefixe}
	trigger:
		if event-member has role named {@staff}:
			send "Din support er nu sluttet. Vi håber du fik den hjælp du søgte." to event-channel with {@botname}
			wait 1 tick
			send "Din support sag vil blive slette om 5 timer" to event-channel with {@botname}
			delete event-message with "{@botname}"
			wait 5 hours
			delete discord entity event-channel with "{@botname}"

command /link:
	trigger:
		set {_e} to random 8 char string from charset `a-zA-Z0-9`
		set {code::%{_e}%} to player
		message "Din kode til at linke din minecraft account til discord er %{_e}%"

discord command link [<text>]:
	prefixes: {@prefixe}
	trigger:
		if arg 1 is "ingame":
			send "Med (ingame) menes da at du skal gå ind på server og skive /link" to event-channel with {@botname} and store the message in {_besked5}
			wait {@delay1} seconds
			delete event-message
			purge {_besked5} with "{@botname}"
		if arg 1 is not set:
			send "Indsæt den link code du fik inde på servern, vis du ikke har en kode kan du skrive /link ingame." to event-channel with {@botname} and store the message in {_besked3}
			wait {@delay1} seconds
			delete event-message
			purge {_besked3} with "{@botname}"
		else if {code::%arg 1%} is not set:
			send "Gå ind på server og skriv /link for at få din code" to event-channel with {@botname} and store the message in {_besked2}
			wait {@delay1} seconds
			delete event-message
			purge {_besked2} with "{@botname}"
		else if {code::%arg 1%} is set:
			set {discord::%discord id of event-member%::player} to {code::%arg-1%}
			set {discord::%discord id of event-member%} to discord id of event-member
			send "Din minecraft account: %{code::%arg-1%}% er nu linket til din Discord account!" to event-channel with {@botname} and store the message in {_besked1}
			delete {code::%arg-1%}
			wait {@delay1} seconds
			delete event-message
			purge {_besked1} with "{@botname}"

discord command bot-watch <text>:
	prefixes: {@prefixe}
	trigger:
		mark event-bot as watching arg-1

discord command bot-play <text>:
	prefixes: {@prefixe}
	trigger:
		mark event-bot as playing arg-1

discord command bot-stream <text> <text>:
	prefixes: {@prefixe}
	trigger:
		mark event-bot as streaming arg-1 with url arg-2

discord command bot-listen <text>:
	prefixes: {@prefixe}
	trigger:
		mark event-bot as listening to arg-1

discord command clear <text>:
	aliases: clearmessages
	prefixes: {@prefixe}
	executable in: guild
	bots: {@bot}
	trigger:
		if discord id of event-user is {@admins}:
			set {_count} to arg-1 parsed as number
			if {_count} is greater than 0:
				grab the last {_count} messages in event-channel
				purge the grabbed messages with event-bot
				reply with "Det ønsket antal beskeder er slettet!" and store the message in {_message}
				wait 2 seconds
				delete random message of {_message} with event-bot
			else:
				reply with ":x: Usage:  **%used prefix%**%used command% **<**a positive number**>**"
		else:
			reply with ":x: Only administrators can use this command!"

discord command hjælp <text>:
	aliases: help, commands, command, kommandoer, kommando
	prefixes: {@prefixe}
	trigger:
		if arg-1 is not set:
			create embed:
				set the title of embed to title with text "Commands"
				set the colour of the embed to Cyan
				add split field named "Commands" with value "!link %nl% !hjælp %nl% !suppport" to embed
				add split field named "Beskrivelse" with value "Du kan linke din minecraft Konto med din discord konto%nl%få at få denne besked igen%nl%kan kun skrive inde i support-ticked. Du vil så oprette en support sag" to embed
				set the timestamp of embed to now
			send the last created embed to event-channel with {@botname}
		if arg-1 is "link":
			create embed:
				set the title of embed to title with text "link af kontoer"
				set the colour of the embed to Cyan
				set the description of embed to "Beskrivelse:%nl%Du kan med denne command link din minecraft konto til din Discord konto%nl%%nl%How to%nl%Gå ind på server og skriv /link%nl%Du vil så modtage en code%nl%Som du nu bruger ve dat gå ind på discorden og skrive /link <kode>"
			send the last created embed to event-channel with {@botname}

discord command support:
	prefixes: {@prefixe}
	trigger:
		if discord id of event-channel is "{@channelid}":
			if channel with name "ticket-%event-user%" exist:
				send "Nej nej. Det kan du ikke" to event-channel with {@botname} and store the message in {_re}
				wait {@delay} seconds
				purge {_re} with "{@botname}"
				delete event-message with {@botname}
				stop
			add 1 to {ticket::%event-guild%}
			wait 1 tick
			set {_ticketname} to "ticket-%{ticket::%event-guild%}%"
			wait 1 tick
			create text channel:
				set name of the channel to "%{_ticketname}%"
				set the topic of channel to "%event-user%'s Support Ticket"
				set the parent of the channel to category named "{@kategori1}"
				create channel in event-guild and store it in {_channel}
			wait 15 ticks
			deny public role of event-guild permission view channel in {_channel} with {@botname}
			allow event-member permissions (message history, view channel, message read, message write, message embed links and message attach files) in {_channel} with {@botname}
			allow role named {@staff}, role named {@mod} and role named {@hjælper} permissions (message history, view channel, message read, message write, message embed links and message attach files) in {_channel} with {@botname}
			wait 1 tick
			send "Support Nummer %{_ticketname}% Er nu oprette gå ned i %{_ticketname}% og afvent hjælp" to event-channel with {@botname} and store the message in {_var}
			wait {@delay} seconds
			purge {_var} with "{@botname}"
			delete event-message with {@botname}
			create embed:
				set the title of embed to "Ticket"
				set the description of embed to "Hey **%mention tag of event-member%** Skriv dit problem her og vent på vores staff time kommer og hjælper dig."
				set the thumbnail of embed to "%avatar of event-member%"
				set the color of embed to dark purple
				set the footer of embed to a footer with text "Åbnet af %event-member%##%discriminator of event-user%"
				set the timestamp of embed to now
				send the last created embed to event-channel with {@botname}
```

**Comment by Pirat0303** [comment]
my skript version is 2.4.1
