### ISSUE TITLE
Lavaplayer error

### ISSUE THREAD

**Issue by slimmers424** [iBlitzkriegi/Vixio#247]
I have an error of lavaplayer he can't find the song that I try to play

**Comment by ilsubyeega** [comment]
Please fill form that this repo provides

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Information**
Skript version: 
Vixio version: 
Minecraft Version: 
Server software name and version:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by slimmers424** [comment]
Information
Skript version: 2.4.1
Vixio version: 2.0.4
Minecraft Version: 1.15.2
Server software name and version: Papercraft 1.15.2 stable

Error:
[23:39:09] [lava-daemon-pool-playback-1-thread-1/ERROR]: [com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of 68ugkg9RePc
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.io.IOException: Received non-success response code 404
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.validateResponseCode(YoutubeSignatureCipherManager.java:158) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:143) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:81) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[?:?]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[?:?]
	... 4 more

Additional context:
When I use the play function this error come and not able to read some video. If I play a video with low vues its work.

**Comment by iBlitzkriegi** [comment]
Fixed
