### ISSUE TITLE
Cant play Music.

### ISSUE THREAD

**Issue by Thanatos1337-kekw** [iBlitzkriegi/Vixio#265]
**Describe the bug**
Cant play Music with Vixio

**To Reproduce**
1. Usin the same script as me, throws 0 erros just warns. 

**Information**
Skript version: latest stable version 2.4.1
Vixio version:  2.0.4
Minecraft Version:  Paper 1.15.2, tried it on 1.8 and 1.12.
Server software name and version: Paper 1.15.2 build 379

**Expected behavior**
I expected that the bot plays music.

**Screenshots**
No Screens but Error-Code from Console and skript in Additional context.

**Additional context**
**Script i use:**
options:
    botname: musik
    Token: dont worry, in my script  i got a token

on skript load:
    login to "{@Token}" with the name "{@botname}" 

on track end:
    if event-bot is "{@botname}":
        wait 60 seconds
    if event-bot is not playing:
        make "{@botname}" disconnect from voice
            
discord command play [<text>]:
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        if voice channel of event-member is set:
            if arg 1 is set:
                if arg 1 contains "index" or "start_radio":
                    reply with "**.play** **Format is invalid. Use youtube link.** :x:"
                    stop
                if arg 1 contains "youtube.com" or "youtu.be":
                    join voice channel of event-member
                    play arg-1
                    search youtube for arg-1 and store the results in {_results::*}
                    create embed:
                        set the title of embed to "Now plaing"
                        set the thumbnail of embed to "https://img.youtube.com/vi/%identifier of {_results::1} %/hqdefault.jpg"
                        set the description of embed to "%{_results::1}%"
                        set the footer of embed to footer with text "%event-user%"
                        add field named "Song duration" with value "%difference between position of track event-bot is playing and duration of track event-bot is playing%" to embed
                        set the timestamp of embed to now
                        set the color of embed to green
                    send the last created embed to event-channel with event-bot
                else:
                    search youtube for arg-1 and store the results in {_results::*}
                    purge the event-message with event-bot
                    if {_results::*} is set:
                        join voice channel of event-member
                        play {_results::1}
                        create embed:
                            set the title of embed to "Added to queue"
                            set the thumbnail of embed to "https://img.youtube.com/vi/%identifier of {_results::1} %/hqdefault.jpg"
                            set the footer of embed to footer with text "%event-user%"
                            add field named "Song duration" with value "%duration of {_results::1} %" to embed
                            set description of embed to "%{_results::1}%"
                            set the timestamp of embed to now
                            set the color of embed to green
                        send the last created embed to event-channel with event-bot
                    else:
                        create embed:
                            set the title of embed to "Track not found"
                            set the footer of embed to footer with text "%event-user%"
                            set the timestamp of embed to now
                            set the color of embed to red
                        send the last created embed to event-channel with event-bot
            else:
                reply with "**.play** **Format is invalid. Use track name or youtube link.** :x:"
        else:
            reply with "**Join voice channel**"
 
discord command queue:
    aliases: list
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        set {_queue::*} to queue of event-bot
        set {_num} to -1
        make embed:
            set title of embed to title with text "Queue"
            loop 11 times:
                add 1 to {_num}
                if {_queue::%{_num}%} is set:
                    add field named "-=[%{_num}%]=-" with value "%{_queue::%{_num}%}%" to embed
            set the footer of embed to footer with text "%event-user%"
            set the timestamp of embed to now
            set the color of embed to blue
        reply with last created embed
 
discord command pause:
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        make embed:
            set title of embed to title with text "Paused"
            set description of embed to "%discord name of track event-bot is playing%"
            set the footer of embed to footer with text "%event-user%"
            set the timestamp of embed to now
            set the color of embed to red
        reply with last created embed  
        pause the track event-bot is playing
 
discord command resume:
    prefixes: .
    executable in: guild
    trigger:
        purge the event-message with event-bot
        resume the track event-bot is playing
        make embed:
            set title of embed to title with text "Resumed"
            set description of embed to "%discord name of track event-bot is playing%"
            set the footer of embed to footer with text "%event-user%"
            set the timestamp of embed to now
            set the color of embed to green
        reply with last created embed
 
discord command stop:
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        make embed:
            set title of embed to title with text "Stopped"
            if track "{@botname}" is playing is set:
                set description of embed to "%discord name of track event-bot is playing%"
                set the footer of embed to footer with text "%event-user%"
                set the timestamp of embed to now
                set the color of embed to red
        reply with last created embed
        stop the track event-bot is playing
        make "{@botname}" disconnect from voice
       
discord command skip:
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        if track "{@botname}" is playing is set:
            make embed:
                set title of embed to title with text "Skipped"
                set description of embed to "%discord name of track event-bot is playing%"
                set the thumbnail of embed to "https://img.youtube.com/vi/%identifier of {_results::1} %/hqdefault.jpg"
                skip the track event-bot is playing
                if track "{@botname}" is playing is set:
                    add split field named "Now playing" with value "%track event-bot is playing%" to embed
                set the footer of embed to footer with text "%event-user%"
                set the thumbnail of embed to "https://img.youtube.com/vi/%identifier of {_results::1} %/hqdefault.jpg"
                set the timestamp of embed to now
                set the color of embed to red
            reply with last created embed
        else:
            make embed:
                set title of embed to title with text "Queue is empty!"
                set the footer of embed to footer with text "%event-user%"
                set the timestamp of embed to now
                set the color of embed to red
            reply with last created embed
 
discord command info:
    prefixes: .
    bots: {@botname}
    executable in: guild
    trigger:
        purge the event-message with event-bot
        if event-bot is playing:
            make embed:
                set title of embed to title with text "%discord name of track event-bot is playing%" and link "%url of track event-bot is playing%"
                set the colour of the embed to green
                add field named "Time remaing" with value "%difference between position of track event-bot is playing and duration of track event-bot is playing%" to embed
                add field named "Author" with value "%authors of track event-bot is playing%" to embed
                set the image of embed to "https://img.youtube.com/vi/%identifier of track event-bot is playing%/hqdefault.jpg"
                set the color of embed to blue
        else:
            make embed:
                set title of embed to title with text "Nothing is played!"
                set the color of embed to red
        reply with last created embed

**Console Error when i try .play youtube-url**
[09:12:38 ERROR]: [com.sedmelluq.discord.lavaplayer.player.AudioPlayer] Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackStartEvent@32c8336a threw an exception.
java.lang.IllegalStateException: TrackEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-379]
at me.iblitzkriegi.vixio.util.audio.TrackScheduler.onTrackStart(TrackScheduler.java:60) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:68) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:350) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.startTrack(DefaultAudioPlayer.java:115) ~[?:?]
at me.iblitzkriegi.vixio.util.audio.TrackScheduler.queue(TrackScheduler.java:26) ~[?:?]
at me.iblitzkriegi.vixio.effects.audio.EffPlay$1.trackLoaded(EffPlay.java:55) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:443) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[09:12:38 ERROR]: [com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of 7XdlhmbaoQU
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:103) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NullPointerException
at java.net.URI$Parser.parse(URI.java:3042) ~[?:1.8.0_242]
at java.net.URI.<init>(URI.java:588) ~[?:1.8.0_242]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:81) ~[?:?]
at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:91) ~[?:?]
... 4 more
[09:12:38 ERROR]: [com.sedmelluq.discord.lavaplayer.player.AudioPlayer] Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@1ff52eac threw an exception.
java.lang.IllegalStateException: TrackEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-379]
at me.iblitzkriegi.vixio.util.audio.TrackScheduler.onTrackEnd(TrackScheduler.java:42) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:70) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:350) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.handleTerminator(DefaultAudioPlayer.java:260) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:196) ~[?:?]
at com.sedmelluq.discord.lavaplayer.track.playback.AudioFrameProviderTools.delegateToTimedProvide(AudioFrameProviderTools.java:18) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:175) ~[?:?]
at me.iblitzkriegi.vixio.util.audio.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:19) ~[?:?]
at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:675) ~[?:?]
at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:665) ~[?:?]
at net.dv8tion.jda.api.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69) ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

This is the end, sorry but the Skript/Error are 2 long 2 get them on a Screen.

**Comment by RasmusHJV2** [comment]
I’m haveing the exact same issue.
