### ISSUE TITLE
Vixio 2.0.6 still no Music.

### ISSUE THREAD

**Issue by DuAnti** [iBlitzkriegi/Vixio#267]
**Describe the bug**
So I updated my Vixio 2 the newest Version 2.0.6 and now the Bot is connectin 2 my voice channel but plays also nothing.

**To Reproduce**
IDK if its only my fault but i will give ya the Error straight outta console.

**Information**
Skript version: 2.4.1
Vixio version: 2.0.6
Minecraft Version: 1.15.2 paper
Server software name and version:

**Expected behavior**

**Screenshots**

**Additional context**
[16:43:41 ERROR]: [com.sedmelluq.discord.lavaplayer.player.AudioPlayer] Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackStartEvent@37015450 threw an exception.
java.lang.IllegalStateException: TrackEvent may only be triggered synchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-384]
at me.iblitzkriegi.vixio.util.audio.TrackScheduler.onTrackStart(TrackScheduler.java:60) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:72) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:368) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.startTrack(DefaultAudioPlayer.java:117) ~[?:?]
at me.iblitzkriegi.vixio.util.audio.TrackScheduler.queue(TrackScheduler.java:26) ~[?:?]
at me.iblitzkriegi.vixio.effects.audio.EffPlay$1.trackLoaded(EffPlay.java:55) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:443) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) ~[?:?]
at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) ~[?:?]
at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by iBlitzkriegi** [comment]
I can't recreate this, have tried multiple times but can't get anything to happen.
