### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by carlodrift** [iBlitzkriegi/Vixio#296]
Hey, I've a strange error since yesterday that causes my bot to stop working. It's not even connected anymore. I haven't made any modification to the code.
```
[10:21:54 WARN]: [Skript] Plugin Skript v2.5.3 generated an exception while executing task 8
java.lang.NullPointerException: null
at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_262]
at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_262]
at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1910) ~[?:?]
at me.iblitzkriegi.vixio.effects.EffLogin.execute(EffLogin.java:70) ~[?:?]
at me.iblitzkriegi.vixio.util.skript.AsyncEffect.access$000(AsyncEffect.java:18) ~[?:?]
at me.iblitzkriegi.vixio.util.skript.AsyncEffect$1.run(AsyncEffect.java:36) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Information**
Skript version: 2.5.3
Vixio version: 2.0.7
Minecraft Version: 1.12.2
Server software name and version: Paper 1618

**Comment by aril3721** [comment]
i have a same problem :<
