### ISSUE TITLE
Vixio isn't working

### ISSUE THREAD

**Issue by ImNotStable** [iBlitzkriegi/Vixio#325]
[01:49:29 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[01:49:32 WARN]: Legacy plugin Vixio v2.0.7 does not specify an api-version.
[01:49:32 INFO]: [Skript] Loading Skript v2.5.3
[01:49:32 INFO]: [Vixio] Loading Vixio v2.0.7
[01:49:32 INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:49:32 INFO]: Preparing level "world"
[01:49:32 INFO]: Preparing start region for dimension minecraft:overworld
[01:49:32 INFO]: Loaded 0 spawn chunks for world world
[01:49:32 INFO]: Time elapsed: 209 ms
[01:49:32 INFO]: Preparing start region for dimension minecraft:the_nether
[01:49:32 INFO]: Loaded 0 spawn chunks for world world_nether
[01:49:32 INFO]: Time elapsed: 158 ms
[01:49:32 INFO]: Preparing start region for dimension minecraft:the_end
[01:49:32 INFO]: Loaded 0 spawn chunks for world world_the_end
[01:49:32 INFO]: Time elapsed: 91 ms
[01:49:32 INFO]: [Skript] Enabling Skript v2.5.3
[01:49:34 INFO]: [Skript] You're currently running the latest stable version of Skript.
[01:49:37 INFO]: [Skript] Loaded 128188 aliases in 3759ms
[01:49:37 INFO]: [Skript]  ~ created by & © Peter Güttinger aka Njol ~
[01:49:37 INFO]: [Vixio] Enabling Vixio v2.0.7*
[01:49:37 ERROR]: Error occurred while enabling Vixio v2.0.7 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.iblitzkriegi.vixio.Vixio.onEnable(Vixio.java:94) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @141236b9
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
        at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
        at me.iblitzkriegi.vixio.util.Util.<clinit>(Util.java:77) ~[?:?]
        ... 11 more
[01:49:37 INFO]: [Vixio] Disabling Vixio v2.0.7
[01:49:37 INFO]: Running delayed init tasks
[01:49:37 INFO]: [Skript] Loading variables...
[01:49:37 WARN]: [Skript] Task #64 for Skript v2.5.3 generated an exception
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:828) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:327) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:513) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:468) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:165) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:119) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        at me.iblitzkriegi.vixio.registration.Types$14.canParse(Types.java:361) ~[?:?]
        at me.iblitzkriegi.vixio.util.skript.SimpleType$1.canParse(SimpleType.java:73) ~[?:?]
        at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:416) ~[?:?]
        at ch.njol.skript.registrations.Classes.parse(Classes.java:449) ~[?:?]
        at ch.njol.skript.variables.VariablesStorage.getValue(VariablesStorage.java:101) ~[?:?]
        at ch.njol.skript.variables.VariablesStorage.load(VariablesStorage.java:158) ~[?:?]
        at ch.njol.skript.variables.Variables.load(Variables.java:191) ~[?:?]
        at ch.njol.skript.Skript$2.run(Skript.java:545) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-731]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1077) ~[patched_1.16.5.jar:git-Paper-731]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-731]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        
I'm not exactly sure what's happening but I made an entirely new server with the latest paper.jar and only Skript and Vixio and this is the error I get

**Comment by carlodrift** [comment]
Install the latest LTS version of Java (11). Vixio isn't Java 16 compatible

**Comment by ImNotStable** [comment]
Alright I'll try that but I'm assuming they'll have to update because isn't paper going to Java 16 for 1.17 or something like that, correct me if I'm wrong

**Comment by 1A3Dev** [comment]
https://github.com/iBlitzkriegi/Vixio/issues/326#issuecomment-858953432
