### ISSUE TITLE
JAVA 16

### ISSUE THREAD

**Issue by myavuzokumus** [iBlitzkriegi/Vixio#326]
**Is your feature request related to a problem? Please describe.**
When can you add JAVA 16 support to the Vixio plugin? Pre-release for 1.17 is out and will be available soon. I would appreciate it if you could make a quick update for JAVA 16.

```
[19:16:38] [Server thread/ERROR]: Error occurred while enabling Vixio v2.0.7 (Is it up to date?)
[19:16:38] [Server thread/ERROR]: Suspected Plugins: 
[19:16:38] [Server thread/ERROR]:     Vixio{enabled,ver=2.0.7,path=plugins\Vixio-2.0.7.jar}
[19:16:38] [Server thread/ERROR]: Exception details below: 
java.lang.ExceptionInInitializerError: null
    at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
    at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
    at me.iblitzkriegi.vixio.Vixio.onEnable(Vixio.java:94) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:595) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:321) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1077) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-117]
    at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3180/0x000000007f1cd370.run(Unknown Source) ~[?:?]
    at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field int java.awt.Color.value accessible: module java.desktop does not "opens java.awt" to unnamed module @f27dff22
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
    at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
    at java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) ~[?:?]
    at java.lang.reflect.Field.setAccessible(Field.java:171) ~[?:?]
    at me.iblitzkriegi.vixio.util.Util.<clinit>(Util.java:77) ~[?:?]
    ... 12 more
[19:16:38] [Server thread/INFO]: [Vixio] Disabling Vixio v2.0.7
```

**Comment by 1A3Dev** [comment]
Try adding `--add-opens java.desktop/java.awt=ALL-UNNAMED` to the start of your server's java arguments.
