### ISSUE TITLE
Vixio refuses to start on 1.18

### ISSUE THREAD

**Issue by Comstepr** [iBlitzkriegi/Vixio#338]
**Describe the bug**

**To Reproduce**
1. Install Paper 1.18.
2. Install Vixio.
(versions of Skript/Paper/Vixio are below)
3. Check console.
4. See error.
```[21:48:00] [Server thread/INFO]: [Vixio] Enabling Vixio v2.0.8*
[21:48:00] [Server thread/ERROR]: Error occurred while enabling Vixio v2.0.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.put(Object, Object)" because "me.iblitzkriegi.vixio.util.skript.EnumMapper.LANG_MAP" is null
        at me.iblitzkriegi.vixio.util.skript.EnumMapper.map(EnumMapper.java:71) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.util.skript.EnumMapper.<init>(EnumMapper.java:64) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.util.skript.EnumMapper.register(EnumMapper.java:33) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.util.skript.EnumMapper.register(EnumMapper.java:28) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.registration.Types.register(Types.java:1008) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.Vixio.setup(Vixio.java:73) ~[Vixio.jar:?]
        at me.iblitzkriegi.vixio.Vixio.onEnable(Vixio.java:89) ~[Vixio.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.18.jar:git-Paper-191]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.18.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:726) ~[paper-1.18.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:501) ~[paper-1.18.jar:git-Paper-191]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[paper-1.18.jar:git-Paper-191]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-191]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:48:00] [Server thread/INFO]: [Vixio] Disabling Vixio v2.0.8
```

**Information**
Skript version: 2.6
Vixio version: 2.0.8
Minecraft Version: 1.18
Server software name and version: Paper 1.18 commit 892c292

**Expected behavior**
Vixio should be working fine.

**Comment by Steak-Fish** [comment]
The plugin is 3 years old
