### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by PARA60N** [iBlitzkriegi/Vixio#75]
### Code: 
```
discord command testme:
  executable in: guild
  bots: {@Bot}
  trigger:
    reply with "yeet"
```
### Error: 
```
[17:50:32 WARN]: [Vixio] Task #27 for Vixio v2.0.0 generated an exception
java.lang.NullPointerException: null
        at me.iblitzkriegi.vixio.commands.DiscordCommand.execute(DiscordCommand.java:72) ~[?:?]
        at me.iblitzkriegi.vixio.commands.CommandListener.lambda$onMessageReceived$0(CommandListener.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-latest.jar:git-Spigot-2086bb0-d0a3620]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```
### Vixio Debug: 
```
{*}------Vixio debug------{*}
Minecraft: git-Spigot-2086bb0-d0a3620 (MC: 1.12.2)
Server: 1.12.2-R0.1-SNAPSHOT
Vixio: 2.0.0
Skript: 2.2-dev37c
{*}---------------------{*}
```

**Comment by iBlitzkriegi** [comment]
Not able to reproduce this issue.
