### ISSUE TITLE
10008: Unknown Message

### ISSUE THREAD

**Issue by PARA60N** [iBlitzkriegi/Vixio#76]
### Warn:
```
[Vixio] Plugin Vixio v2.0.0 generated an exception while executing task 507
net.dv8tion.jda.core.exceptions.ErrorResponseException: 10008: Unknown Message
        at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:148) ~[?:?]
        at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:91) ~[?:?]
        at net.dv8tion.jda.core.entities.MessageChannel$1.handleResponse(MessageChannel.java:900) ~[?:?]
        at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:178) ~[?:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:202) ~[?:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:112) ~[?:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:95) ~[?:?]
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:312) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
        at net.dv8tion.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:129) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```
### Vixio Debug:
```
{*}------Vixio debug------{*}
Minecraft: git-Spigot-2086bb0-d0a3620 (MC: 1.12.2)
Server: 1.12.2-R0.1-SNAPSHOT
Vixio: 2.0.0
Skript: 2.2-dev37c
{*}---------------------{*}
```

**Comment by EnderDev** [comment]
Same thing happens with me if I change the volume, lavaplayer will throw out warnings. And then the server crashes.
